# This is a basic workflow to help you get started with Actions
name: test.yml

on:
  push:
    paths: test/**

jobs:
  build:
   # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    
   # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out
      uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: ./install-deps.sh
      
    - name: Make -C test
      run: make -C test
